version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: opsportal-backend
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: opsportal-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
