
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ops-portal-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
    networks:
      - ops-portal-network

networks:
  ops-portal-network:
    driver: bridge 