services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
    environment:
      - DB_PATH=/app/data/ops.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: 
