version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: opsportal-backend
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: opsportal-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
